/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.5
*/

import { Contract, Interface } from "fuels";
import type {
  Provider,
  Account,
  StorageSlot,
  AbstractAddress,
  BigNumberish,
  BN,
  FunctionFragment,
  InvokeFunction,
} from 'fuels';

import type { Option, Enum, Vec } from "./common";

export enum AccessErrorInput { NotOwner = 'NotOwner' };
export enum AccessErrorOutput { NotOwner = 'NotOwner' };
export enum ErrorInput { CommisionAlwaysLessThan10 = 'CommisionAlwaysLessThan10', NotValidNFTContractId = 'NotValidNFTContractId', CallerNotNFTOwner = 'CallerNotNFTOwner', OwnerNotInitialized = 'OwnerNotInitialized', AmountInvalid = 'AmountInvalid', PriceIsInvalid = 'PriceIsInvalid', InvalidContractIdOrSubId = 'InvalidContractIdOrSubId', NFTInvalid = 'NFTInvalid', NFTAlreadyListed = 'NFTAlreadyListed', InvalidListingId = 'InvalidListingId', OrderClosed = 'OrderClosed', NFTNotListed = 'NFTNotListed', SellerCannotBuy = 'SellerCannotBuy', InvalidQuantity = 'InvalidQuantity', NFTQuantityInvalid = 'NFTQuantityInvalid', InsufficientPayment = 'InsufficientPayment', AdminNotInitialized = 'AdminNotInitialized', OnlySeller = 'OnlySeller', NFTQuantityCannotChange = 'NFTQuantityCannotChange', InsufficientAssetAmount = 'InsufficientAssetAmount', ModifyListingFailed = 'ModifyListingFailed' };
export enum ErrorOutput { CommisionAlwaysLessThan10 = 'CommisionAlwaysLessThan10', NotValidNFTContractId = 'NotValidNFTContractId', CallerNotNFTOwner = 'CallerNotNFTOwner', OwnerNotInitialized = 'OwnerNotInitialized', AmountInvalid = 'AmountInvalid', PriceIsInvalid = 'PriceIsInvalid', InvalidContractIdOrSubId = 'InvalidContractIdOrSubId', NFTInvalid = 'NFTInvalid', NFTAlreadyListed = 'NFTAlreadyListed', InvalidListingId = 'InvalidListingId', OrderClosed = 'OrderClosed', NFTNotListed = 'NFTNotListed', SellerCannotBuy = 'SellerCannotBuy', InvalidQuantity = 'InvalidQuantity', NFTQuantityInvalid = 'NFTQuantityInvalid', InsufficientPayment = 'InsufficientPayment', AdminNotInitialized = 'AdminNotInitialized', OnlySeller = 'OnlySeller', NFTQuantityCannotChange = 'NFTQuantityCannotChange', InsufficientAssetAmount = 'InsufficientAssetAmount', ModifyListingFailed = 'ModifyListingFailed' };
export type IdentityInput = Enum<{ Address: AddressInput, ContractId: ContractIdInput }>;
export type IdentityOutput = Enum<{ Address: AddressOutput, ContractId: ContractIdOutput }>;
export enum InitializationErrorInput { CannotReinitialized = 'CannotReinitialized' };
export enum InitializationErrorOutput { CannotReinitialized = 'CannotReinitialized' };
export enum NFTStandardInput { NFT = 'NFT', SEMI_FT = 'SEMI_FT' };
export enum NFTStandardOutput { NFT = 'NFT', SEMI_FT = 'SEMI_FT' };
export enum ReentrancyErrorInput { NonReentrant = 'NonReentrant' };
export enum ReentrancyErrorOutput { NonReentrant = 'NonReentrant' };
export type StateInput = Enum<{ Uninitialized: undefined, Initialized: IdentityInput, Revoked: undefined }>;
export type StateOutput = Enum<{ Uninitialized: void, Initialized: IdentityOutput, Revoked: void }>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type AssetIdInput = { bits: string };
export type AssetIdOutput = AssetIdInput;
export type BuyerInput = { buyer: IdentityInput, quantity_bought: BigNumberish, buy_price_per_item: BigNumberish };
export type BuyerOutput = { buyer: IdentityOutput, quantity_bought: BN, buy_price_per_item: BN };
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type ListingInput = { order_id: BigNumberish, seller: IdentityInput, nft_contract: ContractIdInput, asset_id: AssetIdInput, token_id: string, price: BigNumberish, quantity: BigNumberish, standard: NFTStandardInput };
export type ListingOutput = { order_id: BN, seller: IdentityOutput, nft_contract: ContractIdOutput, asset_id: AssetIdOutput, token_id: string, price: BN, quantity: BN, standard: NFTStandardOutput };
export type OrderBuyInput = { buyer: IdentityInput, order: ListingInput };
export type OrderBuyOutput = { buyer: IdentityOutput, order: ListingOutput };
export type OrderCancelledInput = { order: ListingInput };
export type OrderCancelledOutput = { order: ListingOutput };
export type OrderListedInput = { order: ListingInput };
export type OrderListedOutput = { order: ListingOutput };
export type OrderUpdatedInput = { order: ListingInput };
export type OrderUpdatedOutput = { order: ListingOutput };
export type OwnershipSetInput = { new_owner: IdentityInput };
export type OwnershipSetOutput = { new_owner: IdentityOutput };
export type OwnershipTransferredInput = { new_owner: IdentityInput, previous_owner: IdentityInput };
export type OwnershipTransferredOutput = { new_owner: IdentityOutput, previous_owner: IdentityOutput };

const abi = {
  "programType": "contract",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "()",
      "concreteTypeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
    },
    {
      "type": "b256",
      "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
    },
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "enum interface::Error",
      "concreteTypeId": "0fe12ec05d225d08dc236ce4be213977fa8c3aeb6ecf2ea110db0c98562addbf",
      "metadataTypeId": 0
    },
    {
      "type": "enum interface::NFTStandard",
      "concreteTypeId": "c984e6ce5860713c46055c41b15e3208ac989f19f8cb28a14907056bfce9181d",
      "metadataTypeId": 1
    },
    {
      "type": "enum standards::src5::AccessError",
      "concreteTypeId": "3f702ea3351c9c1ece2b84048006c8034a24cbc2bad2e740d0412b4172951d3d",
      "metadataTypeId": 2
    },
    {
      "type": "enum standards::src5::State",
      "concreteTypeId": "192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c",
      "metadataTypeId": 3
    },
    {
      "type": "enum std::identity::Identity",
      "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335",
      "metadataTypeId": 4
    },
    {
      "type": "enum std::option::Option<struct interface::Listing>",
      "concreteTypeId": "8fed1de5de157d3c4f4ef8394d0836a50ae9da0050753b77bf2d9cdd0bc97463",
      "metadataTypeId": 5,
      "typeArguments": [
        "f1bbda08bb538e8732336deb2af25888830f411eec649e37dcf67e9be6b49f2b"
      ]
    },
    {
      "type": "enum sway_libs::ownership::errors::InitializationError",
      "concreteTypeId": "1dfe7feadc1d9667a4351761230f948744068a090fe91b1bc6763a90ed5d3893",
      "metadataTypeId": 6
    },
    {
      "type": "enum sway_libs::reentrancy::errors::ReentrancyError",
      "concreteTypeId": "4d216c57b3357523323f59401c7355785b41bdf832f6e1106272186b94797038",
      "metadataTypeId": 7
    },
    {
      "type": "struct interface::Buyer",
      "concreteTypeId": "57de938934a0262bf8ccf0dbac460bfa06d07a64e4309d3a55ad47dfdd9e985d",
      "metadataTypeId": 10
    },
    {
      "type": "struct interface::Listing",
      "concreteTypeId": "f1bbda08bb538e8732336deb2af25888830f411eec649e37dcf67e9be6b49f2b",
      "metadataTypeId": 11
    },
    {
      "type": "struct interface::OrderBuy",
      "concreteTypeId": "41809b993a2b7998d3c394b0c76f825a59775024524a1697848ea98580c2ee7e",
      "metadataTypeId": 12
    },
    {
      "type": "struct interface::OrderCancelled",
      "concreteTypeId": "24189fa21e2a019b0768ddbe2100cec46e9994f7cdde3c72e535885d6006494e",
      "metadataTypeId": 13
    },
    {
      "type": "struct interface::OrderListed",
      "concreteTypeId": "691e7123048b74c552d3a53e73e348d426325c390be7bd4ef2297af30436a5b8",
      "metadataTypeId": 14
    },
    {
      "type": "struct interface::OrderUpdated",
      "concreteTypeId": "52850bd86d8b56413b4a88f152bd3e544cc3f2af89798dd7cce0406fbde987ef",
      "metadataTypeId": 15
    },
    {
      "type": "struct std::asset_id::AssetId",
      "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974",
      "metadataTypeId": 17
    },
    {
      "type": "struct std::contract_id::ContractId",
      "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54",
      "metadataTypeId": 18
    },
    {
      "type": "struct std::vec::Vec<struct interface::Buyer>",
      "concreteTypeId": "4fa2e5c5646bbc9771c1436b7542e53bfb9eec7c476b03bb49659bb3acccc78b",
      "metadataTypeId": 20,
      "typeArguments": [
        "57de938934a0262bf8ccf0dbac460bfa06d07a64e4309d3a55ad47dfdd9e985d"
      ]
    },
    {
      "type": "struct sway_libs::ownership::events::OwnershipSet",
      "concreteTypeId": "e1ef35033ea9d2956f17c3292dea4a46ce7d61fdf37bbebe03b7b965073f43b5",
      "metadataTypeId": 21
    },
    {
      "type": "struct sway_libs::ownership::events::OwnershipTransferred",
      "concreteTypeId": "b3fffbcb3158d7c010c31b194b60fb7857adb4ad61bdcf4b8b42958951d9f308",
      "metadataTypeId": 22
    },
    {
      "type": "u256",
      "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [
    {
      "type": "enum interface::Error",
      "metadataTypeId": 0,
      "components": [
        {
          "name": "CommisionAlwaysLessThan10",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NotValidNFTContractId",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "CallerNotNFTOwner",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "OwnerNotInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "AmountInvalid",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "PriceIsInvalid",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InvalidContractIdOrSubId",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NFTInvalid",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NFTAlreadyListed",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InvalidListingId",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "OrderClosed",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NFTNotListed",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "SellerCannotBuy",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InvalidQuantity",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NFTQuantityInvalid",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InsufficientPayment",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "AdminNotInitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "OnlySeller",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "NFTQuantityCannotChange",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "InsufficientAssetAmount",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "ModifyListingFailed",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum interface::NFTStandard",
      "metadataTypeId": 1,
      "components": [
        {
          "name": "NFT",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "SEMI_FT",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum standards::src5::AccessError",
      "metadataTypeId": 2,
      "components": [
        {
          "name": "NotOwner",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum standards::src5::State",
      "metadataTypeId": 3,
      "components": [
        {
          "name": "Uninitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Initialized",
          "typeId": 4
        },
        {
          "name": "Revoked",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum std::identity::Identity",
      "metadataTypeId": 4,
      "components": [
        {
          "name": "Address",
          "typeId": 16
        },
        {
          "name": "ContractId",
          "typeId": 18
        }
      ]
    },
    {
      "type": "enum std::option::Option",
      "metadataTypeId": 5,
      "components": [
        {
          "name": "None",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        },
        {
          "name": "Some",
          "typeId": 8
        }
      ],
      "typeParameters": [
        8
      ]
    },
    {
      "type": "enum sway_libs::ownership::errors::InitializationError",
      "metadataTypeId": 6,
      "components": [
        {
          "name": "CannotReinitialized",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "enum sway_libs::reentrancy::errors::ReentrancyError",
      "metadataTypeId": 7,
      "components": [
        {
          "name": "NonReentrant",
          "typeId": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d"
        }
      ]
    },
    {
      "type": "generic T",
      "metadataTypeId": 8
    },
    {
      "type": "raw untyped ptr",
      "metadataTypeId": 9
    },
    {
      "type": "struct interface::Buyer",
      "metadataTypeId": 10,
      "components": [
        {
          "name": "buyer",
          "typeId": 4
        },
        {
          "name": "quantity_bought",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "buy_price_per_item",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ]
    },
    {
      "type": "struct interface::Listing",
      "metadataTypeId": 11,
      "components": [
        {
          "name": "order_id",
          "typeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "seller",
          "typeId": 4
        },
        {
          "name": "nft_contract",
          "typeId": 18
        },
        {
          "name": "asset_id",
          "typeId": 17
        },
        {
          "name": "token_id",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "price",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "quantity",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "standard",
          "typeId": 1
        }
      ]
    },
    {
      "type": "struct interface::OrderBuy",
      "metadataTypeId": 12,
      "components": [
        {
          "name": "buyer",
          "typeId": 4
        },
        {
          "name": "order",
          "typeId": 11
        }
      ]
    },
    {
      "type": "struct interface::OrderCancelled",
      "metadataTypeId": 13,
      "components": [
        {
          "name": "order",
          "typeId": 11
        }
      ]
    },
    {
      "type": "struct interface::OrderListed",
      "metadataTypeId": 14,
      "components": [
        {
          "name": "order",
          "typeId": 11
        }
      ]
    },
    {
      "type": "struct interface::OrderUpdated",
      "metadataTypeId": 15,
      "components": [
        {
          "name": "order",
          "typeId": 11
        }
      ]
    },
    {
      "type": "struct std::address::Address",
      "metadataTypeId": 16,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::asset_id::AssetId",
      "metadataTypeId": 17,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::contract_id::ContractId",
      "metadataTypeId": 18,
      "components": [
        {
          "name": "bits",
          "typeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        }
      ]
    },
    {
      "type": "struct std::vec::RawVec",
      "metadataTypeId": 19,
      "components": [
        {
          "name": "ptr",
          "typeId": 9
        },
        {
          "name": "cap",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        8
      ]
    },
    {
      "type": "struct std::vec::Vec",
      "metadataTypeId": 20,
      "components": [
        {
          "name": "buf",
          "typeId": 19,
          "typeArguments": [
            {
              "name": "",
              "typeId": 8
            }
          ]
        },
        {
          "name": "len",
          "typeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "typeParameters": [
        8
      ]
    },
    {
      "type": "struct sway_libs::ownership::events::OwnershipSet",
      "metadataTypeId": 21,
      "components": [
        {
          "name": "new_owner",
          "typeId": 4
        }
      ]
    },
    {
      "type": "struct sway_libs::ownership::events::OwnershipTransferred",
      "metadataTypeId": 22,
      "components": [
        {
          "name": "new_owner",
          "typeId": 4
        },
        {
          "name": "previous_owner",
          "typeId": 4
        }
      ]
    }
  ],
  "functions": [
    {
      "inputs": [],
      "name": "owner",
      "output": "192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "listing_id",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "quantity",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "buy_nft",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "listing_id",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ],
      "name": "cancel_listing",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "new_owner",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "name": "change_admin",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_admin_fee",
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "listing_id",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ],
      "name": "get_buyers",
      "output": "4fa2e5c5646bbc9771c1436b7542e53bfb9eec7c476b03bb49659bb3acccc78b",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "contract_id",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        }
      ],
      "name": "get_commission_percentage",
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "get_current_listing_id",
      "output": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "listing_id",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        }
      ],
      "name": "get_listing",
      "output": "8fed1de5de157d3c4f4ef8394d0836a50ae9da0050753b77bf2d9cdd0bc97463",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "user",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        },
        {
          "name": "contract_id",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        },
        {
          "name": "asset",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "name": "has_user_listed_nft_before",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "admin",
          "concreteTypeId": "ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335"
        }
      ],
      "name": "init",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "nft_contract_id",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        },
        {
          "name": "price",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "token_id",
          "concreteTypeId": "7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b"
        },
        {
          "name": "quantity",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "standard",
          "concreteTypeId": "c984e6ce5860713c46055c41b15e3208ac989f19f8cb28a14907056bfce9181d"
        }
      ],
      "name": "list_nft",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "listing_id",
          "concreteTypeId": "1b5759d94094368cfd443019e7ca5ec4074300e544e5ea993a979f5da627261e"
        },
        {
          "name": "new_price",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "qtyToAdd",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "modify_listing",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        },
        {
          "name": "payable",
          "arguments": []
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "fee",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "set_admin_fee",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [
        {
          "name": "nft_contract_id",
          "concreteTypeId": "29c10735d33b5159f0c71ee1dbd17b36a3e69e41f00fab0d42e1bd9f428d8a54"
        },
        {
          "name": "percentage",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        },
        {
          "name": "asset_id",
          "concreteTypeId": "c0710b6731b1dd59799cf6bef33eee3b3b04a2e40e80a0724090215bbf2ca974"
        }
      ],
      "name": "set_commission_percentage",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read",
            "write"
          ]
        }
      ]
    },
    {
      "inputs": [],
      "name": "withdraw_funds",
      "output": "2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d",
      "attributes": [
        {
          "name": "storage",
          "arguments": [
            "read"
          ]
        }
      ]
    }
  ],
  "loggedTypes": [
    {
      "logId": "5557842539076482339",
      "concreteTypeId": "4d216c57b3357523323f59401c7355785b41bdf832f6e1106272186b94797038"
    },
    {
      "logId": "1144247184059948296",
      "concreteTypeId": "0fe12ec05d225d08dc236ce4be213977fa8c3aeb6ecf2ea110db0c98562addbf"
    },
    {
      "logId": "4719943491892509080",
      "concreteTypeId": "41809b993a2b7998d3c394b0c76f825a59775024524a1697848ea98580c2ee7e"
    },
    {
      "logId": "2601004303446049179",
      "concreteTypeId": "24189fa21e2a019b0768ddbe2100cec46e9994f7cdde3c72e535885d6006494e"
    },
    {
      "logId": "4571204900286667806",
      "concreteTypeId": "3f702ea3351c9c1ece2b84048006c8034a24cbc2bad2e740d0412b4172951d3d"
    },
    {
      "logId": "12970362301975156672",
      "concreteTypeId": "b3fffbcb3158d7c010c31b194b60fb7857adb4ad61bdcf4b8b42958951d9f308"
    },
    {
      "logId": "2161305517876418151",
      "concreteTypeId": "1dfe7feadc1d9667a4351761230f948744068a090fe91b1bc6763a90ed5d3893"
    },
    {
      "logId": "16280289466020123285",
      "concreteTypeId": "e1ef35033ea9d2956f17c3292dea4a46ce7d61fdf37bbebe03b7b965073f43b5"
    },
    {
      "logId": "7574616018497795269",
      "concreteTypeId": "691e7123048b74c552d3a53e73e348d426325c390be7bd4ef2297af30436a5b8"
    },
    {
      "logId": "5946171907191297601",
      "concreteTypeId": "52850bd86d8b56413b4a88f152bd3e544cc3f2af89798dd7cce0406fbde987ef"
    }
  ],
  "messagesTypes": [],
  "configurables": []
};

const storageSlots: StorageSlot[] = [
  {
    "key": "431a0ffd43c2d6ce5c6c6b925f2cee1be3bcb0dc951e0ff636e977eef83d618d",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  },
  {
    "key": "b95b87d7f0f5f3b1a266dcf85e22f058315ecd0b4a6ac991f051d6a1b7c5f8fd",
    "value": "0000000000000000000000000000000000000000000000000000000000000000"
  }
];

export class NftMarketplaceInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    owner: FunctionFragment;
    buy_nft: FunctionFragment;
    cancel_listing: FunctionFragment;
    change_admin: FunctionFragment;
    get_admin_fee: FunctionFragment;
    get_buyers: FunctionFragment;
    get_commission_percentage: FunctionFragment;
    get_current_listing_id: FunctionFragment;
    get_listing: FunctionFragment;
    has_user_listed_nft_before: FunctionFragment;
    init: FunctionFragment;
    list_nft: FunctionFragment;
    modify_listing: FunctionFragment;
    set_admin_fee: FunctionFragment;
    set_commission_percentage: FunctionFragment;
    withdraw_funds: FunctionFragment;
  };
}

export class NftMarketplace extends Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: NftMarketplaceInterface;
  declare functions: {
    owner: InvokeFunction<[], StateOutput>;
    buy_nft: InvokeFunction<[listing_id: BigNumberish, quantity: BigNumberish], void>;
    cancel_listing: InvokeFunction<[listing_id: BigNumberish], void>;
    change_admin: InvokeFunction<[new_owner: IdentityInput], void>;
    get_admin_fee: InvokeFunction<[], BN>;
    get_buyers: InvokeFunction<[listing_id: BigNumberish], Vec<BuyerOutput>>;
    get_commission_percentage: InvokeFunction<[contract_id: ContractIdInput], BN>;
    get_current_listing_id: InvokeFunction<[], BN>;
    get_listing: InvokeFunction<[listing_id: BigNumberish], Option<ListingOutput>>;
    has_user_listed_nft_before: InvokeFunction<[user: IdentityInput, contract_id: ContractIdInput, asset: AssetIdInput], boolean>;
    init: InvokeFunction<[admin: IdentityInput], void>;
    list_nft: InvokeFunction<[nft_contract_id: ContractIdInput, price: BigNumberish, token_id: string, quantity: BigNumberish, standard: NFTStandardInput], void>;
    modify_listing: InvokeFunction<[listing_id: BigNumberish, new_price: BigNumberish, qtyToAdd: BigNumberish], void>;
    set_admin_fee: InvokeFunction<[fee: BigNumberish], void>;
    set_commission_percentage: InvokeFunction<[nft_contract_id: ContractIdInput, percentage: BigNumberish, asset_id: AssetIdInput], void>;
    withdraw_funds: InvokeFunction<[], void>;
  };

  constructor(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider,
  ) {
    super(id, abi, accountOrProvider);
  }
}
