/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.94.5
*/

export { NftMarketplace } from './NftMarketplace';
export { NftMarketplaceFactory } from './NftMarketplaceFactory';
